//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriversGalaxy.OSMigrationTool.Restore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriversGalaxy.OSMigrationTool.Restore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverData.zip file not found.
        /// </summary>
        internal static string DriverDataNotFound {
            get {
                return ResourceManager.GetString("DriverDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverData.xml file not found.
        /// </summary>
        internal static string DriverDataXMLNotFound {
            get {
                return ResourceManager.GetString("DriverDataXMLNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers installed.
        /// </summary>
        internal static string DriversInstalled {
            get {
                return ResourceManager.GetString("DriversInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers to install.
        /// </summary>
        internal static string DriversToInstall {
            get {
                return ResourceManager.GetString("DriversToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string FacebookLike {
            get {
                return ResourceManager.GetString("FacebookLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/facebook.
        /// </summary>
        internal static string FBUrl {
            get {
                return ResourceManager.GetString("FBUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE FREE PREMIUM SOFTWARE.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -77.
        /// </summary>
        internal static string GoogleMargin {
            get {
                return ResourceManager.GetString("GoogleMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/googleplus.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing driver -.
        /// </summary>
        internal static string InstallingDriver {
            get {
                return ResourceManager.GetString("InstallingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing drivers.
        /// </summary>
        internal static string InstallingDrivers {
            get {
                return ResourceManager.GetString("InstallingDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing progress.
        /// </summary>
        internal static string InstallingProgress {
            get {
                return ResourceManager.GetString("InstallingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS mismatch.
        /// </summary>
        internal static string OSMismatch {
            get {
                return ResourceManager.GetString("OSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to install the drivers for {0} at the {1}.
        ///Please, generate the drivers migration package for the correct OS version..
        /// </summary>
        internal static string OSMismatchText {
            get {
                return ResourceManager.GetString("OSMismatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post this on:.
        /// </summary>
        internal static string PostOn {
            get {
                return ResourceManager.GetString("PostOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://pallysoft.com/driversgalaxy/.
        /// </summary>
        internal static string RootUrl {
            get {
                return ResourceManager.GetString("RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one driver to install..
        /// </summary>
        internal static string SelectAtLeastOneDriver {
            get {
                return ResourceManager.GetString("SelectAtLeastOneDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drivers to install.
        /// </summary>
        internal static string SelectDrivers {
            get {
                return ResourceManager.GetString("SelectDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Install&quot; to install the drivers.
        /// </summary>
        internal static string SelectDriversToInstallFooter {
            get {
                return ResourceManager.GetString("SelectDriversToInstallFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Install&quot; to install the drivers for the destination OS.
        /// </summary>
        internal static string SelectDriversToInstallFooterText {
            get {
                return ResourceManager.GetString("SelectDriversToInstallFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -50.
        /// </summary>
        internal static string TweetMargin {
            get {
                return ResourceManager.GetString("TweetMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/twitter.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically. Please open this Link in your favorite browser:.
        /// </summary>
        internal static string UrlCannotBeOpenedMessage {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically.
        /// </summary>
        internal static string UrlCannotBeOpenedTitle {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedTitle", resourceCulture);
            }
        }
    }
}
