//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriversGalaxy.OSMigrationTool.Backup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriversGalaxy.OSMigrationTool.Backup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers composed.
        /// </summary>
        internal static string AllDriversComposed {
            get {
                return ResourceManager.GetString("AllDriversComposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelCompose {
            get {
                return ResourceManager.GetString("CancelCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Scan.
        /// </summary>
        internal static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary downloading folder - Documents/Freemium Utilites/Downloads
        /// is not accessible. Please run this app with admin privilegies..
        /// </summary>
        internal static string CheckDownloadFolder {
            get {
                return ResourceManager.GetString("CheckDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Preferences.
        /// </summary>
        internal static string CheckPreferences {
            get {
                return ResourceManager.GetString("CheckPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the destination directory.
        /// </summary>
        internal static string ChooseDestination {
            get {
                return ResourceManager.GetString("ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose the destination directory.
        /// </summary>
        internal static string ChooseDestinationDirectory {
            get {
                return ResourceManager.GetString("ChooseDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose the destination OS.
        /// </summary>
        internal static string ChooseDestinationOS {
            get {
                return ResourceManager.GetString("ChooseDestinationOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the destination OS.
        /// </summary>
        internal static string ChooseDestOS {
            get {
                return ResourceManager.GetString("ChooseDestOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose drivers to download.
        /// </summary>
        internal static string ChooseDriversToDownload {
            get {
                return ResourceManager.GetString("ChooseDriversToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your destination OS.
        /// </summary>
        internal static string ChooseOS {
            get {
                return ResourceManager.GetString("ChooseOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        internal static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing driver -.
        /// </summary>
        internal static string ComposingDriver {
            get {
                return ResourceManager.GetString("ComposingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing drivers.
        /// </summary>
        internal static string ComposingDrivers {
            get {
                return ResourceManager.GetString("ComposingDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPOSING PROGRESS.
        /// </summary>
        internal static string ComposingProgress {
            get {
                return ResourceManager.GetString("ComposingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting Server.
        /// </summary>
        internal static string ContactingServer {
            get {
                return ResourceManager.GetString("ContactingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed .
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers downloaded.
        ///Now press the Compose button below to create a drivers installation utility for the destination OS, which will be saved in a place that you&apos;ve choosen..
        /// </summary>
        internal static string DownloadFinishedPressCompose {
            get {
                return ResourceManager.GetString("DownloadFinishedPressCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading driver for: .
        /// </summary>
        internal static string DownloadingDriver {
            get {
                return ResourceManager.GetString("DownloadingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading drivers.
        /// </summary>
        internal static string DownloadingDrivers {
            get {
                return ResourceManager.GetString("DownloadingDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        internal static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Scan.
        /// </summary>
        internal static string DriverScan {
            get {
                return ResourceManager.GetString("DriverScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers downloaded.
        /// </summary>
        internal static string DriversDownloaded {
            get {
                return ResourceManager.GetString("DriversDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers ready to download.
        /// </summary>
        internal static string DriversReadyToDownload {
            get {
                return ResourceManager.GetString("DriversReadyToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string FacebookLike {
            get {
                return ResourceManager.GetString("FacebookLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/facebook.
        /// </summary>
        internal static string FBUrl {
            get {
                return ResourceManager.GetString("FBUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE FREE PREMIUM SOFTWARE.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -77.
        /// </summary>
        internal static string GoogleMargin {
            get {
                return ResourceManager.GetString("GoogleMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/googleplus.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drivers to download.
        /// </summary>
        internal static string NoDriversToDownload {
            get {
                return ResourceManager.GetString("NoDriversToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now composing:.
        /// </summary>
        internal static string NowComposing {
            get {
                return ResourceManager.GetString("NowComposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now scanning:.
        /// </summary>
        internal static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post this on:.
        /// </summary>
        internal static string PostOn {
            get {
                return ResourceManager.GetString("PostOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://pallysoft.com/driversgalaxy/.
        /// </summary>
        internal static string RootUrl {
            get {
                return ResourceManager.GetString("RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save drivers to.
        /// </summary>
        internal static string SaveDriversTo {
            get {
                return ResourceManager.GetString("SaveDriversTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan drivers.
        /// </summary>
        internal static string ScanDrivers {
            get {
                return ResourceManager.GetString("ScanDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan finished.
        /// </summary>
        internal static string ScanFinishTitle {
            get {
                return ResourceManager.GetString("ScanFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your system.
        /// </summary>
        internal static string ScanFooter {
            get {
                return ResourceManager.GetString("ScanFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press scan to see the drivers that can be backuped.
        /// </summary>
        internal static string ScanFooterText {
            get {
                return ResourceManager.GetString("ScanFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string ScanForIssues {
            get {
                return ResourceManager.GetString("ScanForIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning device -.
        /// </summary>
        internal static string ScanningDevice {
            get {
                return ResourceManager.GetString("ScanningDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN PROGRESS.
        /// </summary>
        internal static string ScanProgress {
            get {
                return ResourceManager.GetString("ScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your system.
        /// </summary>
        internal static string ScanSystem {
            get {
                return ResourceManager.GetString("ScanSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one driver to download.
        /// </summary>
        internal static string SelectAtLeastOneDriver {
            get {
                return ResourceManager.GetString("SelectAtLeastOneDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Download&quot; to get the drivers.
        /// </summary>
        internal static string SelectDriversToDownloadFooter {
            get {
                return ResourceManager.GetString("SelectDriversToDownloadFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Download&quot; to get the drivers for the destination OS.
        /// </summary>
        internal static string SelectDriversToDownloadFooterText {
            get {
                return ResourceManager.GetString("SelectDriversToDownloadFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for downloads.
        /// </summary>
        internal static string SelectFolderForDownloads {
            get {
                return ResourceManager.GetString("SelectFolderForDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OS.
        /// </summary>
        internal static string SelectOS {
            get {
                return ResourceManager.GetString("SelectOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one operation system..
        /// </summary>
        internal static string SelectOSToScan {
            get {
                return ResourceManager.GetString("SelectOSToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting downloading drivers.
        /// </summary>
        internal static string StartingDriversDownload {
            get {
                return ResourceManager.GetString("StartingDriversDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this tool should do is scan the users drivers and download the matching driver from our database, but not for his current os, instead it will be for the os that he migrates to.
        /// </summary>
        internal static string ToolDescription {
            get {
                return ResourceManager.GetString("ToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -50.
        /// </summary>
        internal static string TweetMargin {
            get {
                return ResourceManager.GetString("TweetMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/twitter.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically. Please open this Link in your favorite browser:.
        /// </summary>
        internal static string UrlCannotBeOpenedMessage {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically.
        /// </summary>
        internal static string UrlCannotBeOpenedTitle {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedTitle", resourceCulture);
            }
        }
    }
}
