//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriversGalaxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriversGalaxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Access to the world&apos;s largest driver database.
        /// </summary>
        internal static string AccessDriverDatabase {
            get {
                return ResourceManager.GetString("AccessDriverDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers are up to date!.
        /// </summary>
        internal static string AllDriversAreUpToDate {
            get {
                return ResourceManager.GetString("AllDriversAreUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a license key? Enter here and update all drivers now!.
        /// </summary>
        internal static string AlreadyHaveKey {
            get {
                return ResourceManager.GetString("AlreadyHaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: Your drivers need to be updated!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play it safe. Driver Galaxy helps update your drivers, automatically!.
        /// </summary>
        internal static string AttentionFooterText {
            get {
                return ResourceManager.GetString("AttentionFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Scan.
        /// </summary>
        internal static string AutomatedScan {
            get {
                return ResourceManager.GetString("AutomatedScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Update Drivers.
        /// </summary>
        internal static string AutoUpdateDrivers {
            get {
                return ResourceManager.GetString("AutoUpdateDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; Restore.
        /// </summary>
        internal static string BackupAndRestore {
            get {
                return ResourceManager.GetString("BackupAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup finished.
        /// </summary>
        internal static string BackupFinished {
            get {
                return ResourceManager.GetString("BackupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the exclusions you created in the Driver Scan.
        /// </summary>
        internal static string BackupFinishedText {
            get {
                return ResourceManager.GetString("BackupFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupRadioBtnTitle {
            get {
                return ResourceManager.GetString("BackupRadioBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup all or specifiy the device drivers of your system, in order to create copies of these drivers that you can revert to later. .
        /// </summary>
        internal static string BackupText {
            get {
                return ResourceManager.GetString("BackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP  TYPE.
        /// </summary>
        internal static string BackupType {
            get {
                return ResourceManager.GetString("BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open programs before continuing with the driver update.
        ///It is possible that the screen may turn black during this update for a short period of time..
        /// </summary>
        internal static string BeforeDriverUpdateMessage {
            get {
                return ResourceManager.GetString("BeforeDriverUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Best Price Guarantee.
        /// </summary>
        internal static string BestPrice {
            get {
                return ResourceManager.GetString("BestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL SCAN.
        /// </summary>
        internal static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check Backups folder in your Preferences.
        /// </summary>
        internal static string CheckBackupsFolder {
            get {
                return ResourceManager.GetString("CheckBackupsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your download folder in preferences.
        /// </summary>
        internal static string CheckDownloadFolder {
            get {
                return ResourceManager.GetString("CheckDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Preferences.
        /// </summary>
        internal static string CheckPreferences {
            get {
                return ResourceManager.GetString("CheckPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the destination directory.
        /// </summary>
        internal static string ChooseDestination {
            get {
                return ResourceManager.GetString("ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose the destination directory.
        /// </summary>
        internal static string ChooseDestinationDirectory {
            get {
                return ResourceManager.GetString("ChooseDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button behaviour:.
        /// </summary>
        internal static string CloseButtonBehaviour {
            get {
                return ResourceManager.GetString("CloseButtonBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting Server to check updates.
        /// </summary>
        internal static string ContactingServer {
            get {
                return ResourceManager.GetString("ContactingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day:.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of current version:.
        /// </summary>
        internal static string DetailCurrentDriverDate {
            get {
                return ResourceManager.GetString("DetailCurrentDriverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DetailName {
            get {
                return ResourceManager.GetString("DetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of new version:.
        /// </summary>
        internal static string DetailNewDriverDate {
            get {
                return ResourceManager.GetString("DetailNewDriverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed .
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete!.
        /// </summary>
        internal static string DownloadCompleteMessage {
            get {
                return ResourceManager.GetString("DownloadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Driver.
        /// </summary>
        internal static string DownloadDriver {
            get {
                return ResourceManager.GetString("DownloadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading driver for: .
        /// </summary>
        internal static string DownloadingDriver {
            get {
                return ResourceManager.GetString("DownloadingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        internal static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Information Details.
        /// </summary>
        internal static string DriverDetailInfoPopupTitle {
            get {
                return ResourceManager.GetString("DriverDetailInfoPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVER DETAILS.
        /// </summary>
        internal static string DriverDetails {
            get {
                return ResourceManager.GetString("DriverDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Downloading &amp; Installation.
        /// </summary>
        internal static string DriverDownloadingAndInstallation {
            get {
                return ResourceManager.GetString("DriverDownloadingAndInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} excluded from scans.
        /// </summary>
        internal static string DriverExcluded {
            get {
                return ResourceManager.GetString("DriverExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DriverGalaxy {
            get {
                object obj = ResourceManager.GetObject("DriverGalaxy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Info.
        /// </summary>
        internal static string DriverInfo {
            get {
                return ResourceManager.GetString("DriverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver list is still loading.
        /// </summary>
        internal static string DriverListLoading {
            get {
                return ResourceManager.GetString("DriverListLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver list is still being loaded in the background. Please wait a moment and then try the backup again..
        /// </summary>
        internal static string DriverListLoadingText {
            get {
                return ResourceManager.GetString("DriverListLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of {0} drivers is completed..
        /// </summary>
        internal static string DriversBackupedSuccesfully {
            get {
                return ResourceManager.GetString("DriversBackupedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Scan.
        /// </summary>
        internal static string DriverScan {
            get {
                return ResourceManager.GetString("DriverScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Scan Results.
        /// </summary>
        internal static string DriverScanResults {
            get {
                return ResourceManager.GetString("DriverScanResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers downloaded.
        /// </summary>
        internal static string DriversDownloaded {
            get {
                return ResourceManager.GetString("DriversDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers restored successfully.
        /// </summary>
        internal static string DriversRestoredSuccesfully {
            get {
                return ResourceManager.GetString("DriversRestoredSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Update.
        /// </summary>
        internal static string DriverUpdate {
            get {
                return ResourceManager.GetString("DriverUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        internal static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        internal static string EveryWeek {
            get {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude device.
        /// </summary>
        internal static string ExcludeDevice {
            get {
                return ResourceManager.GetString("ExcludeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from scans.
        /// </summary>
        internal static string ExcludeFromScans {
            get {
                return ResourceManager.GetString("ExcludeFromScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string FacebookLike {
            get {
                return ResourceManager.GetString("FacebookLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Fast secure updates without searching.
        /// </summary>
        internal static string FastUpdate {
            get {
                return ResourceManager.GetString("FastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/facebook.
        /// </summary>
        internal static string FBUrl {
            get {
                return ResourceManager.GetString("FBUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Report.
        /// </summary>
        internal static string FeedbackReport {
            get {
                return ResourceManager.GetString("FeedbackReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/contact/fdc/.
        /// </summary>
        internal static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE FREE PREMIUM SOFTWARE.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from scans?.
        /// </summary>
        internal static string FromScans {
            get {
                return ResourceManager.GetString("FromScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -77.
        /// </summary>
        internal static string GoogleMargin {
            get {
                return ResourceManager.GetString("GoogleMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/googleplus.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to · Keeps your hardware runnininng, forever.
        /// </summary>
        internal static string HardwareRun {
            get {
                return ResourceManager.GetString("HardwareRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string InitialLoading {
            get {
                return ResourceManager.GetString("InitialLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLATION PROGRESS.
        /// </summary>
        internal static string InstallationProgress {
            get {
                return ResourceManager.GetString("InstallationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing driver for:.
        /// </summary>
        internal static string InstallingDriver {
            get {
                return ResourceManager.GetString("InstallingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always keep your drivers up to date!.
        /// </summary>
        internal static string KeepUpToDate {
            get {
                return ResourceManager.GetString("KeepUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scan:.
        /// </summary>
        internal static string LastScan {
            get {
                return ResourceManager.GetString("LastScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch at startup.
        /// </summary>
        internal static string LaunchAtStartup {
            get {
                return ResourceManager.GetString("LaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Scan Exclusions.
        /// </summary>
        internal static string ManageScanExclusions {
            get {
                return ResourceManager.GetString("ManageScanExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the exclusions you created in the Driver Scan.
        /// </summary>
        internal static string ManageScanExclusionsText {
            get {
                return ResourceManager.GetString("ManageScanExclusionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Backup (Full).
        /// </summary>
        internal static string ManualBackupFull {
            get {
                return ResourceManager.GetString("ManualBackupFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Backup (Selected Drivers).
        /// </summary>
        internal static string ManualBackupSelected {
            get {
                return ResourceManager.GetString("ManualBackupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        internal static string MinToTray {
            get {
                return ResourceManager.GetString("MinToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than.
        /// </summary>
        internal static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now scanning:.
        /// </summary>
        internal static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 12.03.
        /// </summary>
        internal static string OSMigrationToolPopupBackupSubTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupBackupSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Migration Tool Backup Tool.
        /// </summary>
        internal static string OSMigrationToolPopupBackupTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 12.03.
        /// </summary>
        internal static string OSMigrationToolPopupRestoreSubTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupRestoreSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Migration Tool Restore Tool.
        /// </summary>
        internal static string OSMigrationToolPopupRestoreTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupRestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Migration Tool.
        /// </summary>
        internal static string OSMigrationToolPopupTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outdated drivers found.
        /// </summary>
        internal static string OutdatedDriversFound {
            get {
                return ResourceManager.GetString("OutdatedDriversFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated drivers updated!.
        /// </summary>
        internal static string OutdatedDriversUpdated {
            get {
                return ResourceManager.GetString("OutdatedDriversUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post this on:.
        /// </summary>
        internal static string PostOn {
            get {
                return ResourceManager.GetString("PostOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application settings.
        /// </summary>
        internal static string PreferencesFooter {
            get {
                return ResourceManager.GetString("PreferencesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit applications preferences and settings from this panel.
        /// </summary>
        internal static string PreferencesFooterText {
            get {
                return ResourceManager.GetString("PreferencesFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot later.
        /// </summary>
        internal static string RebootLater {
            get {
                return ResourceManager.GetString("RebootLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now.
        /// </summary>
        internal static string RebootNow {
            get {
                return ResourceManager.GetString("RebootNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot required.
        /// </summary>
        internal static string RebootRequired {
            get {
                return ResourceManager.GetString("RebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        internal static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart your computer.
        /// </summary>
        internal static string RestartYourComputer {
            get {
                return ResourceManager.GetString("RestartYourComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore drivers.
        /// </summary>
        internal static string RestoreDrivers {
            get {
                return ResourceManager.GetString("RestoreDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed.
        /// </summary>
        internal static string RestoreFailedCaption {
            get {
                return ResourceManager.GetString("RestoreFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the restore of the selected drivers failed..
        /// </summary>
        internal static string RestoreFailedText {
            get {
                return ResourceManager.GetString("RestoreFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreRadioBtnTitle {
            get {
                return ResourceManager.GetString("RestoreRadioBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore system drivers of one of the backups that you created earlier..
        /// </summary>
        internal static string RestoreText {
            get {
                return ResourceManager.GetString("RestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://freemium.com/driversgalaxy/.
        /// </summary>
        internal static string RootUrl {
            get {
                return ResourceManager.GetString("RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore drivers.
        /// </summary>
        internal static string RunOSMigrationRestoreTool {
            get {
                return ResourceManager.GetString("RunOSMigrationRestoreTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run OS Migration Tool.
        /// </summary>
        internal static string RunOSMigrationTool {
            get {
                return ResourceManager.GetString("RunOSMigrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backups to this folder:.
        /// </summary>
        internal static string SaveBackupsTo {
            get {
                return ResourceManager.GetString("SaveBackupsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save downloaded drivers to this folder:.
        /// </summary>
        internal static string SaveDownloadedTo {
            get {
                return ResourceManager.GetString("SaveDownloadedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan:.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &amp; Update Drivers.
        /// </summary>
        internal static string ScanAndUpdateDrivers {
            get {
                return ResourceManager.GetString("ScanAndUpdateDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed.
        /// </summary>
        internal static string ScanCompleted {
            get {
                return ResourceManager.GetString("ScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Exclusions.
        /// </summary>
        internal static string ScanExclusions {
            get {
                return ResourceManager.GetString("ScanExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your system regularly.
        /// </summary>
        internal static string ScanFooter {
            get {
                return ResourceManager.GetString("ScanFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular maintenance will help to improve system performance.
        /// </summary>
        internal static string ScanFooterText {
            get {
                return ResourceManager.GetString("ScanFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN FOR ISSUES.
        /// </summary>
        internal static string ScanForIssues {
            get {
                return ResourceManager.GetString("ScanForIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning device -.
        /// </summary>
        internal static string ScanningDevice {
            get {
                return ResourceManager.GetString("ScanningDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN PROGRESS.
        /// </summary>
        internal static string ScanProgress {
            get {
                return ResourceManager.GetString("ScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Backup type.
        /// </summary>
        internal static string SelectBackupType {
            get {
                return ResourceManager.GetString("SelectBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select backup type to proceed..
        /// </summary>
        internal static string SelectBackupTypeText {
            get {
                return ResourceManager.GetString("SelectBackupTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select devices.
        /// </summary>
        internal static string SelectDevices {
            get {
                return ResourceManager.GetString("SelectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select devices you no longer wish to exclude from the scan..
        /// </summary>
        internal static string SelectDevicesToRemoveFromExclude {
            get {
                return ResourceManager.GetString("SelectDevicesToRemoveFromExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drivers.
        /// </summary>
        internal static string SelectDrivers {
            get {
                return ResourceManager.GetString("SelectDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DRIVERS FOR BACKUP.
        /// </summary>
        internal static string SelectDriversForBackup {
            get {
                return ResourceManager.GetString("SelectDriversForBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why should I create Backups?.
        /// </summary>
        internal static string SelectDriversForBackupFooter {
            get {
                return ResourceManager.GetString("SelectDriversForBackupFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can restore these driver later if needed.
        /// </summary>
        internal static string SelectDriversForBackupFooterText {
            get {
                return ResourceManager.GetString("SelectDriversForBackupFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DRIVERS FOR RESTORE.
        /// </summary>
        internal static string SelectDriversForRestore {
            get {
                return ResourceManager.GetString("SelectDriversForRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drivers for restore.
        /// </summary>
        internal static string SelectDriversForRestoreCaption {
            get {
                return ResourceManager.GetString("SelectDriversForRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one driver for restore..
        /// </summary>
        internal static string SelectDriversForRestoreText {
            get {
                return ResourceManager.GetString("SelectDriversForRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one driver to backup..
        /// </summary>
        internal static string SelectDriversToBackup {
            get {
                return ResourceManager.GetString("SelectDriversToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select at least one driver to update..
        /// </summary>
        internal static string SelectDriversToUpdate {
            get {
                return ResourceManager.GetString("SelectDriversToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DriverData.zip.
        /// </summary>
        internal static string SelectDriversZip {
            get {
                return ResourceManager.GetString("SelectDriversZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select the folder for storing driver backups.
        /// </summary>
        internal static string SelectFolderForBackups {
            get {
                return ResourceManager.GetString("SelectFolderForBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select the folder for driver downloads.
        /// </summary>
        internal static string SelectFolderForDownloads {
            get {
                return ResourceManager.GetString("SelectFolderForDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select DriverData.zip.
        /// </summary>
        internal static string SelectMigrationDriversZip {
            get {
                return ResourceManager.GetString("SelectMigrationDriversZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIBE TO DRIVERS GALAXY NOW.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME &amp; DATE.
        /// </summary>
        internal static string TimeAndDate {
            get {
                return ResourceManager.GetString("TimeAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSize.
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -50.
        /// </summary>
        internal static string TweetMargin {
            get {
                return ResourceManager.GetString("TweetMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.freemium.com/fsu/twitter.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver update process completed for driver:.
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver update process failed for driver.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to update driver.
        /// </summary>
        internal static string UpdateStart {
            get {
                return ResourceManager.GetString("UpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only € 0,99 / month.
        /// </summary>
        internal static string UpgradeFooter {
            get {
                return ResourceManager.GetString("UpgradeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel your subscription any time..
        /// </summary>
        internal static string UpgradeFooterText {
            get {
                return ResourceManager.GetString("UpgradeFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Now.
        /// </summary>
        internal static string UpgradeNow {
            get {
                return ResourceManager.GetString("UpgradeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically. Please open this Link in your favorite browser:.
        /// </summary>
        internal static string UrlCannotBeOpenedMessage {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link cannot be opened automatically.
        /// </summary>
        internal static string UrlCannotBeOpenedTitle {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why should I create Backups?.
        /// </summary>
        internal static string WhyCreateBackups {
            get {
                return ResourceManager.GetString("WhyCreateBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the exclusions you created in the Driver Scan.
        /// </summary>
        internal static string WhyCreateBackupsText {
            get {
                return ResourceManager.GetString("WhyCreateBackupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows startup behaviour:.
        /// </summary>
        internal static string WindowsStartup {
            get {
                return ResourceManager.GetString("WindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freemium Driver Utilites Scan.
        /// </summary>
        internal static string WindowsTaskRegistrationInfo {
            get {
                return ResourceManager.GetString("WindowsTaskRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key not valid. Please try again!.
        /// </summary>
        internal static string WrongLicenseKey {
            get {
                return ResourceManager.GetString("WrongLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your advantages:.
        /// </summary>
        internal static string YourAdvantages {
            get {
                return ResourceManager.GetString("YourAdvantages", resourceCulture);
            }
        }
    }
}
